### ISSUE TITLE
Cannot pass the tests after adding new tokens

### ISSUE THREAD

**Issue by evgygor** [TwitchBronBron/brightscript-parser#1]
Hi, I created the [fork ](https://github.com/evgygor/brightscript-parser) of brightscript-parser
and I added support for conditional compile if/else statements:
**#if, #else, #else if, #end if**.

I named the tokens: **condIf, condElse, condElseIf, condEndIf.**
When I run the tests, its failed with the following errors:

```
nyc mocha src/**/*.spec.ts --full-trace --bail

  √ all tokens are placed into a bucket
  √ all tokens have a token definition
  BrightscriptLexer
    getMatch() works for --
      √ endFunction
      √ endIf
      √ endSub
      √ endWhile
      √ exitWhile
      √ exitFor
      √ endFor
      √ elseIf
      1) condElseIf

  10 passing (73ms)
  1 failing

  1) BrightscriptLexer
       getMatch() works for --
         condElseIf:

      Expected 'identifier' to equal 'condElseIf' for 'condelseif'
      + expected - actual

      -identifier
      +condElseIf

      at matchMany (C:\Git_works\brightscript-parser\src\BrightscriptLexer.spec.ts:17:49)
      at Context.<anonymous> (C:\Git_works\brightscript-parser\src\BrightscriptLexer.spec.ts:39:9)
      at callFn (C:\Git_works\brightscript-parser\node_modules\mocha\lib\runnable.js:372:21)
      at Test.Runnable.run (C:\Git_works\brightscript-parser\node_modules\mocha\lib\runnable.js:364:7)
      at Runner.runTest (C:\Git_works\brightscript-parser\node_modules\mocha\lib\runner.js:455:10)
      at C:\Git_works\brightscript-parser\node_modules\mocha\lib\runner.js:573:12
      at next (C:\Git_works\brightscript-parser\node_modules\mocha\lib\runner.js:369:14)
      at C:\Git_works\brightscript-parser\node_modules\mocha\lib\runner.js:379:7
      at next (C:\Git_works\brightscript-parser\node_modules\mocha\lib\runner.js:303:14)
      at Immediate._onImmediate (C:\Git_works\brightscript-parser\node_modules\mocha\lib\runner.js:347:5)
      at runCallback (timers.js:696:18)
      at tryOnImmediate (timers.js:667:5)
      at processImmediate (timers.js:649:5)

ERROR: Coverage for lines (86.47%) does not meet global threshold (100%)
ERROR: Coverage for functions (81.82%) does not meet global threshold (100%)
ERROR: Coverage for branches (28.57%) does not meet global threshold (100%)
ERROR: Coverage for statements (86.67%) does not meet global threshold (100%)

===================  Coverage summary ==================
Statements   : 86.67% ( 182/210 )
Branches     : 28.57% ( 4/14 )
Functions    : 81.82% ( 9/11 )
Lines        : 86.47% ( 179/207 )
==================================================
```
I implemented it in the [forked formatter](https://github.com/evgygor/brightscript-formatter) and in forked[ vscode-brightscript-language extension](https://github.com/evgygor/vscode-brightscript-language).
I installed this extension in vscode and its works very well regardless failed tests in brightscript-parser.

Could you please advice about described issue?
Thanks

**Comment by TwitchBronBron** [comment]
I think I found the problem. I'm working on a fix in a local copy of your branch. I'll let you know when I get it fixed up.

**Comment by evgygor** [comment]
Thanks!

**Comment by TwitchBronBron** [comment]
Here's a new commit (in a temporary repository) that shows what I had to do in order to get the tests to pass. https://github.com/TwitchBronBron/brightscript-parser-evgygor/commit/8a12fd2f25c729067e0d107fbc3fe6fd74290952

**Comment by evgygor** [comment]
> Here's a new commit (in a temporary repository) that shows what I had to do in order to get the tests to pass. [TwitchBronBron/brightscript-parser-evgygor@8a12fd2](https://github.com/TwitchBronBron/brightscript-parser-evgygor/commit/8a12fd2f25c729067e0d107fbc3fe6fd74290952)

I implemented those changes and created the pull request, It's failed on missing reviewer.
Could you please review the PR?
Thanks
